version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: "7G"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}